// 本番環境用：実際のAPIキーを直接設定
// 注意：実際のプロダクションでは環境変数を使用することを推奨
window.SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVyc2ZwYnF3b2x6cXJxZG5rcmhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2Njc3MDMsImV4cCI6MjA2NDI0MzcwM30.XQqtU5jJV4g1oXlovGMjVRyVolswHn1w5BhBAUqPHCk'; 